import test from 'node:test';
import assert from 'node:assert/strict';
import {application,validId,fileMeta,hash,signed,verify,validMagic,endpoint} from '../server/core.js';
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test-server-key';process.env.APP_SECRET='test-secret-not-for-production-'.repeat(2);process.env.APP_ORIGIN='https://admission.example';
export const fixture={firstNameThai:'ทดสอบ',lastNameThai:'ระบบ',firstNameEng:'Test',lastNameEng:'Applicant',idCard:'1101700203450',birthDate:'2005-01-01',gender:'ชาย',nationality:'ไทย',religion:'พุทธ',phone:'0812345678',email:'test@example.com',address:'ข้อมูลทดสอบ',educationLevel:'ม.3',schoolName:'โรงเรียนทดสอบ',schoolProvince:'สมุทรปราการ',graduationYear:'2569',schoolType:'รัฐบาล',courseId:'P001',gpa:'3.50',terms:true};
// Generate a syntactically valid checksum for a synthetic fixture.
const prefix='110170020345';let sum=0;for(let i=0;i<12;i++)sum+=Number(prefix[i])*(13-i);fixture.idCard=prefix+((11-sum%11)%10);
test('validates applicant data and strips client-controlled fields',()=>{const out=application({...fixture,applicationNumber:'FORGED',courseName:'FORGED'});assert.equal(out.gpa,3.5);assert.ok(!('applicationNumber'in out));assert.ok(!('courseName'in out));});
test('rejects invalid ID, date, GPA and missing consent',()=>{assert.equal(validId('0000000000000'),false);for(const patch of [{idCard:'0000000000000'},{birthDate:'2005-02-31'},{gpa:'3.5junk'},{terms:false},{phone:'123'},{email:'bad'}])assert.throws(()=>application({...fixture,...patch}));});
test('upload proof is bound to signed contents and expiry',()=>{const token=signed({path:'staging/test.pdf',exp:Date.now()+60000});assert.equal(verify(token).path,'staging/test.pdf');assert.throws(()=>verify('e30.'+token.split('.')[1]));assert.throws(()=>verify(signed({exp:1})));});
test('file allowlist and magic validation reject spoofed documents',()=>{const bytes=Buffer.from('%PDF-1.7\nfixture');assert.ok(validMagic(bytes,'application/pdf'));assert.equal(validMagic(Buffer.from('<html>'),'application/pdf'),false);assert.throws(()=>fileMeta({name:'x',type:'text/html',size:5,sha256:hash(bytes)}));assert.throws(()=>fileMeta({name:'x',type:'application/pdf',size:5242881,sha256:hash(bytes)}));});
test('API rejects cross-origin writes before processing',async()=>{let called=false;const handler=endpoint('POST',async()=>{called=true;return {};});const res={setHeader(){},end(value){this.body=JSON.parse(value);}};await handler({method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:{}},res);assert.equal(res.statusCode,403);assert.equal(called,false);});
